development:
  adapter: postgresql
  database: message
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: message_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: message_production
  pool: 5
  timeout: 5000

